//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BotonesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BotonesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyResources.BotonesResources", typeof(BotonesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btn btn-delete glyphicon glyphicon-remove.
        /// </summary>
        public static string BotonBorrar {
            get {
                return ResourceManager.GetString("BotonBorrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btn btn-create glyphicon glyphicon-plus.
        /// </summary>
        public static string BotonCrear {
            get {
                return ResourceManager.GetString("BotonCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btn btn-edit glyphicon glyphicon-pencil.
        /// </summary>
        public static string BotonEditar {
            get {
                return ResourceManager.GetString("BotonEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btn btn-save glyphicon glyphicon-floppy-disk.
        /// </summary>
        public static string BotonGuardar {
            get {
                return ResourceManager.GetString("BotonGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btn btn-link btn-block.
        /// </summary>
        public static string BotonLink {
            get {
                return ResourceManager.GetString("BotonLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to color:red.
        /// </summary>
        public static string ColorBorrar {
            get {
                return ResourceManager.GetString("ColorBorrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to color:green.
        /// </summary>
        public static string ColorCrear {
            get {
                return ResourceManager.GetString("ColorCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to color:blue.
        /// </summary>
        public static string ColorEditar {
            get {
                return ResourceManager.GetString("ColorEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to color:lightblue.
        /// </summary>
        public static string ColorGuardar {
            get {
                return ResourceManager.GetString("ColorGuardar", resourceCulture);
            }
        }
    }
}
