//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LibroResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LibroResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyResources.LibroResources", typeof(LibroResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar libro.
        /// </summary>
        public static string AccionBorrar {
            get {
                return ResourceManager.GetString("AccionBorrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear libro.
        /// </summary>
        public static string AccionCrear {
            get {
                return ResourceManager.GetString("AccionCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar libro.
        /// </summary>
        public static string AccionEditar {
            get {
                return ResourceManager.GetString("AccionEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar libro.
        /// </summary>
        public static string AccionGuardar {
            get {
                return ResourceManager.GetString("AccionGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo.
        /// </summary>
        public static string DatoCodigo {
            get {
                return ResourceManager.GetString("DatoCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titulo.
        /// </summary>
        public static string DatoTitulo {
            get {
                return ResourceManager.GetString("DatoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado por Titulo.
        /// </summary>
        public static string ElementoListadoCabecera {
            get {
                return ResourceManager.GetString("ElementoListadoCabecera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestión de libros.
        /// </summary>
        public static string ElementoTituloPagina {
            get {
                return ResourceManager.GetString("ElementoTituloPagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libro:.
        /// </summary>
        public static string ElementoToken {
            get {
                return ResourceManager.GetString("ElementoToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede borrar porque hay ejemplares dependientes..
        /// </summary>
        public static string ErrorBorrarTieneEjemplares {
            get {
                return ResourceManager.GetString("ErrorBorrarTieneEjemplares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al crear el libro.
        /// </summary>
        public static string ErrorCrear {
            get {
                return ResourceManager.GetString("ErrorCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha podido borrar el libro.
        /// </summary>
        public static string ErrorDelete {
            get {
                return ResourceManager.GetString("ErrorDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al editar el libro.
        /// </summary>
        public static string ErrorEditar {
            get {
                return ResourceManager.GetString("ErrorEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha encontrado el libro en la BBDD.
        /// </summary>
        public static string ErrorItemNoEncontrado {
            get {
                return ResourceManager.GetString("ErrorItemNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe el libro seleccionado.
        /// </summary>
        public static string ErrorItemNoExiste {
            get {
                return ResourceManager.GetString("ErrorItemNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha podido acceder al libro.
        /// </summary>
        public static string ErrorVistaDetalle {
            get {
                return ResourceManager.GetString("ErrorVistaDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El libro se ha creado correctamente.
        /// </summary>
        public static string ExitoCrear {
            get {
                return ResourceManager.GetString("ExitoCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El libro se ha borrado correctamente.
        /// </summary>
        public static string ExitoDelete {
            get {
                return ResourceManager.GetString("ExitoDelete", resourceCulture);
            }
        }
    }
}
