//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PrestamoResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PrestamoResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyResources.PrestamoResources", typeof(PrestamoResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar prestamo.
        /// </summary>
        public static string AccionBorrar {
            get {
                return ResourceManager.GetString("AccionBorrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear prestamo.
        /// </summary>
        public static string AccionCrear {
            get {
                return ResourceManager.GetString("AccionCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar prestamo.
        /// </summary>
        public static string AccionEditar {
            get {
                return ResourceManager.GetString("AccionEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar prestamo .
        /// </summary>
        public static string AccionGuardar {
            get {
                return ResourceManager.GetString("AccionGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo.
        /// </summary>
        public static string DatoCodigo {
            get {
                return ResourceManager.GetString("DatoCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de devolucion.
        /// </summary>
        public static string DatoFDevolucion {
            get {
                return ResourceManager.GetString("DatoFDevolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de recogida.
        /// </summary>
        public static string DatoFRecogida {
            get {
                return ResourceManager.GetString("DatoFRecogida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isbn.
        /// </summary>
        public static string DatoIsbn {
            get {
                return ResourceManager.GetString("DatoIsbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libro.
        /// </summary>
        public static string DatoLibro {
            get {
                return ResourceManager.GetString("DatoLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titulo.
        /// </summary>
        public static string DatoTitulo {
            get {
                return ResourceManager.GetString("DatoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string DatoUsuario {
            get {
                return ResourceManager.GetString("DatoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado de prestamos.
        /// </summary>
        public static string ElementoListadoCabecera {
            get {
                return ResourceManager.GetString("ElementoListadoCabecera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion de prestamos.
        /// </summary>
        public static string ElementoTituloPagina {
            get {
                return ResourceManager.GetString("ElementoTituloPagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prestamo:.
        /// </summary>
        public static string ElementoToken {
            get {
                return ResourceManager.GetString("ElementoToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al crear el prestamo.
        /// </summary>
        public static string ErrorCrear {
            get {
                return ResourceManager.GetString("ErrorCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha podido borrar el prestamo.
        /// </summary>
        public static string ErrorDelete {
            get {
                return ResourceManager.GetString("ErrorDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al editar el prestamo.
        /// </summary>
        public static string ErrorEditar {
            get {
                return ResourceManager.GetString("ErrorEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha encontrado el prestamo en la BBDD.
        /// </summary>
        public static string ErrorItemNoEncontrado {
            get {
                return ResourceManager.GetString("ErrorItemNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe el prestamo seleccionado.
        /// </summary>
        public static string ErrorItemNoExiste {
            get {
                return ResourceManager.GetString("ErrorItemNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha podido acceder al prestamo.
        /// </summary>
        public static string ErrorVistaDetalle {
            get {
                return ResourceManager.GetString("ErrorVistaDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El prestamo se ha creado correctamente.
        /// </summary>
        public static string ExitoCrear {
            get {
                return ResourceManager.GetString("ExitoCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El prestamo se ha borrado correctamente.
        /// </summary>
        public static string ExitoDelete {
            get {
                return ResourceManager.GetString("ExitoDelete", resourceCulture);
            }
        }
    }
}
