//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UsuarioResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UsuarioResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyResources.UsuarioResources", typeof(UsuarioResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar usuario.
        /// </summary>
        public static string AccionBorrar {
            get {
                return ResourceManager.GetString("AccionBorrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear usuario.
        /// </summary>
        public static string AccionCrear {
            get {
                return ResourceManager.GetString("AccionCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar usuario.
        /// </summary>
        public static string AccionEditar {
            get {
                return ResourceManager.GetString("AccionEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar usuario.
        /// </summary>
        public static string AccionGuardar {
            get {
                return ResourceManager.GetString("AccionGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellidos.
        /// </summary>
        public static string DatoApellidos {
            get {
                return ResourceManager.GetString("DatoApellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dni.
        /// </summary>
        public static string DatoDni {
            get {
                return ResourceManager.GetString("DatoDni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string DatoEmail {
            get {
                return ResourceManager.GetString("DatoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de nacimiento.
        /// </summary>
        public static string DatoFnacimiento {
            get {
                return ResourceManager.GetString("DatoFnacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string DatoNombre {
            get {
                return ResourceManager.GetString("DatoNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string DatoPasswd {
            get {
                return ResourceManager.GetString("DatoPasswd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string DatoUsername {
            get {
                return ResourceManager.GetString("DatoUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado de usuarios.
        /// </summary>
        public static string ElementoListadoCabecera {
            get {
                return ResourceManager.GetString("ElementoListadoCabecera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestión de usuarios.
        /// </summary>
        public static string ElementoTituloPagina {
            get {
                return ResourceManager.GetString("ElementoTituloPagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario: .
        /// </summary>
        public static string ElementoToken {
            get {
                return ResourceManager.GetString("ElementoToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al crear el usuario.
        /// </summary>
        public static string ErrorCrear {
            get {
                return ResourceManager.GetString("ErrorCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha podido borrar el usuario.
        /// </summary>
        public static string ErrorDelete {
            get {
                return ResourceManager.GetString("ErrorDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al editar el usuario.
        /// </summary>
        public static string ErrorEditar {
            get {
                return ResourceManager.GetString("ErrorEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha encontrado el usuario en la BBDD.
        /// </summary>
        public static string ErrorItemNoEncontrado {
            get {
                return ResourceManager.GetString("ErrorItemNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe el usuario seleccionado.
        /// </summary>
        public static string ErrorItemNoExiste {
            get {
                return ResourceManager.GetString("ErrorItemNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha podido acceder al usuario.
        /// </summary>
        public static string ErrorVistaDetalle {
            get {
                return ResourceManager.GetString("ErrorVistaDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario se ha creado correctamente.
        /// </summary>
        public static string ExitoCrear {
            get {
                return ResourceManager.GetString("ExitoCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario se ha borrado correctamente.
        /// </summary>
        public static string ExitoDelete {
            get {
                return ResourceManager.GetString("ExitoDelete", resourceCulture);
            }
        }
    }
}
